### ISSUE TITLE
您好，请问AristoRoBERTa-large模型是如何获得的？

### ISSUE THREAD

**Issue by gsxf997** [Yueqing-Sun/JointLK#2]
您好，这篇论文是一个非常棒的工作，我最近也在做OpenBookQA数据集，我发现大多方法都使用了AristoRoBERTa-large模型，请问这个模型您是自己训练的吗？不知道您是否方便提供该模型呢？

**Comment by Yueqing-Sun** [comment]
> 您好，这篇论文是一个非常棒的工作，我最近也在做OpenBookQA数据集，我发现大多方法都使用了AristoRoBERTa-large模型，请问这个模型您是自己训练的吗？不知道您是否方便提供该模型呢？

您好，可以向Aristo team团队发邮件要AristoRoBERTa，但是很遗憾我们在代码中并没有用到它。我们的代码是基于QA-GNN的代码更改的，所以我曾经也像你一样为AristoRoBERTa感到疑惑，也询问过QA-GNN论文的作者，但并未得到回复。但是我们发现了一些细节证明了使用OpenBookQA中提供的fact在RoBERTa上进行训练就相当于使用了AristoRoBERTa（虽然这并不严谨）。
细节一：QA-GNN的脚注“OpenBookQA provides an extra corpus of scientific facts in a textual form. AristoRoBERTa uses the facts corresponding to each question, prepared by Clark et al. (2019), as an additional input to the QA context.”
细节二：在QA-GNN提供的数据中，data/obqa/statement中有"train-fact.statement.jsonl", "dev-fact.statement.jsonl"和"test-fact.statement.jsonl"
细节三：今年ICLR的论文GreaseLM（应该与qagnn是同一个组，同样follow qagnn），它在OpenBookQA上只展示了使用AristoRoBERTa的结果，出于好奇我看了一下它的代码，你可以在preprocess.py中看到对OpenBookQA的处理使用了OpenBookQA-V1-Sep2018/Data/Additional/train_complete.jsonl、OpenBookQA-V1-Sep2018/Data/Additional/dev_complete.jsonl和OpenBookQA-V1-Sep2018/Data/Additional/test_complete.jsonl。
希望我的回答解决了你的疑问，如仍有问题，可以邮件沟通。

**Comment by gsxf997** [comment]
好的，非常感谢！
